### ISSUE TITLE
Child Queries

### ISSUE THREAD

**Issue by matthewnitschke** [matthewnitschke/pulls#9]
Consider a "child query" concept

Ability to add a query as a child of another query. Shows up as a folder that cannot be added to or ungrouped, but can be rearranged

- Children of the folder can be reordered, but not grouped (as long as I dont support multi level groups)
- Folder can be named
- Unable to add other prs to query folder
- Query folder order will be stored in structure, and children order as well
- Don't run query folder query when folder is closed. The act of opening will trigger a query. Once open, showing the dropdown triggers a re-query
- Loading icon in menu item? or number badge in header loading icon
- Possible to batch multiple queries in a single graphQL call?

is defined within settings:
```yaml
queries:
    - label: "My PRs"
      query: "is:pr is:open"
      children:
        - label: "Closed PRs"
          query: "is:pr is:closed"
          sort:
            property: "name" # created | repo | org | 
            direction: "asc" # asc | desc
```
